name: json_bigint
description: A json serializer for dart that supports BigInt.

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  meta: ^1.8.0
  collection: ^1.16.0
  petitparser: ^5.1.0

dev_dependencies:
  lints: ^2.0.0
